### ISSUE TITLE
[建议]关于程序的几点建议

### ISSUE THREAD

**Issue by KKeygen** [PLFJY/id5-login#1]
1. 不要用硬编码的self-hosted gitee地址下载Python，在网上找公开、权威一点的镜像；
2. 同样地，建议不要把上游项目的文件直接嵌入到这个项目里，推荐用[Git: submodule](https://zhuanlan.zhihu.com/p/404615843)子模块与上游同步，或者在启动的时候从权威的镜像下载
3. 建议把第五人格启动这一步让**用户自己**完成（可以打开dwrg所在的文件夹啥的），因为非explorer.exe启动的第五人格可能被反作弊特征/检测
4. run.bat有点问题，容易造成断网。这是我的疏忽，这两周有时间会更新一下。

**Comment by PLFJY** [comment]
部分解决，镜像源摆烂了
